# Generated by Django 4.2.7 on 2023-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_rename_custumer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
