# Generated by Django 4.2.7 on 2023-12-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sdt',
        ),
    ]
