# Generated by Django 4.2.7 on 2023-12-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_customer_email_customer_sdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='123456789', max_length=128),
        ),
    ]
