# Generated by Django 4.2.7 on 2023-12-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
