# Generated by Django 4.2.7 on 2023-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='text_url',
            field=models.TextField(blank=True),
        ),
    ]
